name:   CODEGREEN_DATAVIS

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - flask
    - dash
    - plotly
    - subprocess
    - time
    - webbrowser
    - codecarbon
    - matplotlib
    - psutil
